name: Merge CI
on: [pull_request]
jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        version: [10, 12, 14]
    runs-on: ${{ matrix.os }}    
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
        