name: GitHub Action Demo
On: [ push ]
jobs:
  Test:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The job was autoatically triggered by a ${{ github.event_name }} event."
      - run: python Main.py
      